import Foundation

struct CardInfo: Hashable {
    let name: String
    let hint: String
}

enum CardDatabase {
    static let cards: [CardInfo] = [
        CardInfo(name: "Archer Queen", hint: "invisible"),
        CardInfo(name: "Archers", hint: "duo"),
        CardInfo(name: "Arrows", hint: "sky"),
        CardInfo(name: "Baby Dragon", hint: "splash air"),
        CardInfo(name: "Balloon", hint: "bomb drop"),
        CardInfo(name: "Bandit", hint: "dash"),
        CardInfo(name: "Barbarian Barrel", hint: "roll"),
        CardInfo(name: "Barbarian Hut", hint: "spawn"),
        CardInfo(name: "Barbarians", hint: "swarm"),
        CardInfo(name: "Bats", hint: "cheap air"),
        CardInfo(name: "Battle Healer", hint: "heal"),
        CardInfo(name: "Battle Ram", hint: "charge"),
        CardInfo(name: "Berserker", hint: "rage"),
        CardInfo(name: "Bomb Tower", hint: "defense splash"),
        CardInfo(name: "Bomber", hint: "ground splash"),
        CardInfo(name: "Boss Bandit", hint: "super dash"),
        CardInfo(name: "Bowler", hint: "push"),
        CardInfo(name: "Cannon", hint: "cheap defense"),
        CardInfo(name: "Cannon Cart", hint: "mobile turret"),
        CardInfo(name: "Clone", hint: "duplicate"),
        CardInfo(name: "Dark Prince", hint: "splash charge"),
        CardInfo(name: "Dart Goblin", hint: "long range"),
        CardInfo(name: "Earthquake", hint: "shake buildings"),
        CardInfo(name: "Electro Dragon", hint: "chain stun"),
        CardInfo(name: "Electro Giant", hint: "reflect"),
        CardInfo(name: "Electro Spirit", hint: "zap chain"),
        CardInfo(name: "Electro Wizard", hint: "stun on spawn"),
        CardInfo(name: "Elite Barbarians", hint: "fast duo"),
        CardInfo(name: "Elixir Collector", hint: "pump"),
        CardInfo(name: "Elixir Golem", hint: "refund blobs"),
        CardInfo(name: "Executioner", hint: "boomerang axe"),
        CardInfo(name: "Fire Spirit", hint: "jump splash"),
        CardInfo(name: "Fireball", hint: "knockback"),
        CardInfo(name: "Firecracker", hint: "recoil"),
        CardInfo(name: "Fisherman", hint: "pull"),
        CardInfo(name: "Flying Machine", hint: "air turret"),
        CardInfo(name: "Freeze", hint: "ice stop"),
        CardInfo(name: "Furnace", hint: "spirit spawner"),
        CardInfo(name: "Giant", hint: "tank tower"),
        CardInfo(name: "Giant Skeleton", hint: "death bomb"),
        CardInfo(name: "Giant Snowball", hint: "slow push"),
        CardInfo(name: "Goblin Barrel", hint: "surprise back"),
        CardInfo(name: "Goblin Cage", hint: "brawler"),
        CardInfo(name: "Goblin Curse", hint: "hex"),
        CardInfo(name: "Goblin Demolisher", hint: "siege cart"),
        CardInfo(name: "Goblin Drill", hint: "burrow"),
        CardInfo(name: "Goblin Gang", hint: "mixed swarm"),
        CardInfo(name: "Goblin Giant", hint: "spears escort"),
        CardInfo(name: "Goblin Hut", hint: "spear spawner"),
        CardInfo(name: "Goblin Machine", hint: "contraption"),
        CardInfo(name: "Goblins", hint: "stab trio"),
        CardInfo(name: "Goblinstein", hint: "gob golem"),
        CardInfo(name: "Golden Knight", hint: "chain dash"),
        CardInfo(name: "Golem", hint: "split death"),
        CardInfo(name: "Graveyard", hint: "random spawn"),
        CardInfo(name: "Guards", hint: "shields"),
        CardInfo(name: "Heal Spirit", hint: "burst heal"),
        CardInfo(name: "Hog Rider", hint: "wallbreak jump"),
        CardInfo(name: "Hunter", hint: "close burst"),
        CardInfo(name: "Ice Golem", hint: "death slow"),
        CardInfo(name: "Ice Spirit", hint: "freeze jump"),
        CardInfo(name: "Ice Wizard", hint: "perma slow"),
        CardInfo(name: "Inferno Dragon", hint: "ramping beam"),
        CardInfo(name: "Inferno Tower", hint: "melt beam"),
        CardInfo(name: "Knight", hint: "cheap tank"),
        CardInfo(name: "Lava Hound", hint: "pups"),
        CardInfo(name: "Lightning", hint: "selective strike"),
        CardInfo(name: "Little Prince", hint: "charge shot"),
        CardInfo(name: "Lumberjack", hint: "rage drop"),
        CardInfo(name: "Magic Archer", hint: "pierce line"),
        CardInfo(name: "Mega Knight", hint: "spawn slam"),
        CardInfo(name: "Mega Minion", hint: "heavy air"),
        CardInfo(name: "Mighty Miner", hint: "tunnel swap"),
        CardInfo(name: "Miner", hint: "burrow back"),
        CardInfo(name: "Mini P.E.K.K.A", hint: "pancakes"),
        CardInfo(name: "Minion Horde", hint: "air swarm"),
        CardInfo(name: "Minions", hint: "air trio"),
        CardInfo(name: "Mirror", hint: "repeat higher"),
        CardInfo(name: "Monk", hint: "reflect palms"),
        CardInfo(name: "Mortar", hint: "siege arc"),
        CardInfo(name: "Mother Witch", hint: "cursed hogs"),
        CardInfo(name: "Musketeer", hint: "single shot"),
        CardInfo(name: "Night Witch", hint: "bat spawn"),
        CardInfo(name: "P.E.K.K.A", hint: "heavy hit"),
        CardInfo(name: "Phoenix", hint: "rebirth egg"),
        CardInfo(name: "Poison", hint: "slow melt"),
        CardInfo(name: "Prince", hint: "lance charge"),
        CardInfo(name: "Princess", hint: "long splash"),
        CardInfo(name: "Rage", hint: "speed up"),
        CardInfo(name: "Ram Rider", hint: "snare"),
        CardInfo(name: "Rascals", hint: "trio split"),
        CardInfo(name: "Rocket", hint: "big boom"),
        CardInfo(name: "Royal Delivery", hint: "drop troop"),
        CardInfo(name: "Royal Ghost", hint: "invisible swing"),
        CardInfo(name: "Royal Giant", hint: "longshot tower"),
        CardInfo(name: "Royal Hogs", hint: "lane split"),
        CardInfo(name: "Royal Recruits", hint: "six split"),
        CardInfo(name: "Rune Giant", hint: "mystic smash"),
        CardInfo(name: "Skeleton Army", hint: "bone swarm"),
        CardInfo(name: "Skeleton Barrel", hint: "drop swarm"),
        CardInfo(name: "Skeleton Dragons", hint: "twin air"),
        CardInfo(name: "Skeleton King", hint: "soul summon"),
        CardInfo(name: "Skeletons", hint: "cycle bones"),
        CardInfo(name: "Sparky", hint: "charge blast"),
        CardInfo(name: "Spear Goblins", hint: "poke range"),
        CardInfo(name: "Spirit Empress", hint: "ethereal"),
        CardInfo(name: "Suspicious Bush", hint: "ambush"),
        CardInfo(name: "Tesla", hint: "pop up"),
        CardInfo(name: "The Log", hint: "roll push"),
        CardInfo(name: "Three Musketeers", hint: "triple shot"),
        CardInfo(name: "Tombstone", hint: "on-death bones"),
        CardInfo(name: "Tornado", hint: "group pull"),
        CardInfo(name: "Valkyrie", hint: "spin"),
        CardInfo(name: "Vines", hint: "entangle"),
        CardInfo(name: "Void", hint: "nullify"),
        CardInfo(name: "Wall Breakers", hint: "suicide run"),
        CardInfo(name: "Witch", hint: "skeleton spawn"),
        CardInfo(name: "Wizard", hint: "splash fire"),
        CardInfo(name: "X-Bow", hint: "siege lock"),
        CardInfo(name: "Zap", hint: "instant stun"),
        CardInfo(name: "Zappies", hint: "stagger stun")
    ]

    static var names: [String] { cards.map { $0.name } }

    static func hint(for name: String) -> String? {
        return cards.first(where: { $0.name == name })?.hint
    }
}
